package com.java8Features.flatMapvsMap;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public class FlatMapVsMap {
	public static void main(String[] args) {
		
		List<String> loseWeight = new ArrayList<>(); 
		loseWeight.add("avocados"); loseWeight.add("beans"); loseWeight.add("salad"); loseWeight.add("oats"); loseWeight.add("broccoli");
		System.out.println(loseWeight);
		
		
		List listOfInts = loseWeight.stream()
				.map(s -> s.length()) .collect(Collectors.toList());
		System.out.println(listOfInts);
		
		
		List<List<Integer>> listOfListOfNumber = new ArrayList<>(); 
		listOfListOfNumber.add(Arrays.asList(2, 4)); 
		listOfListOfNumber.add(Arrays.asList(3, 9)); 
		listOfListOfNumber.add(Arrays.asList(4, 16));
		System.out.println("list of list : " + listOfListOfNumber);
		
		
		 List listOfIntegers =  listOfListOfNumber.stream()
				.flatMap( list -> list.stream())
				.collect(Collectors.toList());
		System.out.println("list of numbers generated by flatMap : " + listOfIntegers);

		Set<Integer> listOfIntegers1 =  listOfListOfNumber.stream()
				.flatMap( list -> list.stream())
				.collect(Collectors.toSet());
		System.out.println("An unique list of numbers generated by flatMap : " + listOfIntegers1);
		

	}

}
